import type { Activity, ActivityCategory, Day, Interest, Trip, TravelPace } from '../types';

export const INTERESTS: Interest[] = [
  'Food', 'Culture', 'Nature', 'Adventure', 'History', 'Shopping', 'Hidden Gems', 'Nightlife',
];

export const PACES: TravelPace[] = ['Relaxed', 'Balanced', 'Packed'];

export const CURRENCIES = ['USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD'] as const;

type ActivitySeed = Omit<Activity, 'id' | 'dayId' | 'tripId' | 'locked' | 'notes'>;

function makeDay(
  tripId: string,
  label: string,
  date: string,
  theme: string,
  summary: string,
  seeds: ActivitySeed[],
): Day {
  const dayId = `${tripId}-${label.toLowerCase().replace(/\s+/g, '-')}`;
  return {
    id: dayId,
    tripId,
    label,
    date,
    theme,
    summary,
    activities: seeds.map((a, i) => ({
      ...a,
      id: `${dayId}-${i}`,
      dayId,
      tripId,
      locked: false,
      notes: [],
    })),
  };
}

export const sampleTrips: Trip[] = [
  {
    id: 'tokyo-5d',
    title: 'Tokyo in Five',
    destination: 'Tokyo, Japan',
    startDate: '2026-04-08',
    endDate: '2026-04-12',
    budget: 2400,
    currency: 'USD',
    travelers: 2,
    pace: 'Balanced',
    interests: ['Food', 'Culture', 'History', 'Hidden Gems', 'Nightlife'],
    specialRequests: 'Vegetarian-friendly restaurants. Avoid early mornings.',
    status: 'Planning',
    lastUpdated: '2026-04-01T10:30:00Z',
    isDemo: false,
    days: [
      makeDay('tokyo-5d', 'Day 1', '2026-04-08', 'Arrival & Shinjuku', "Settle in and get your first taste of Tokyo's electric energy.", [
        {
          title: 'Arrival & Shinjuku Stroll',
          description: 'Check in and wander through the neon-lit streets of Shinjuku, popping into convenience stores and soaking in the city at your own pace.',
          time: '14:00',
          location: 'Shinjuku',
          duration: 180,
          cost: 0,
          currency: 'USD',
          category: 'Culture' as ActivityCategory,
          aiReason: 'Settle in and explore the neon heart of Tokyo with minimal planning pressure.',
        },
        {
          title: 'Omoide Yokocho Dinner',
          description: 'Squeeze into one of the tiny yakitori stalls lining this smoky, lantern-lit alley for skewered chicken, grilled vegetables, and cold beer.',
          time: '19:00',
          location: 'Shinjuku',
          duration: 120,
          cost: 45,
          currency: 'USD',
          category: 'Food' as ActivityCategory,
          aiReason: 'A historic alley of yakitori stalls — authentic, affordable, and walkable from your hotel.',
        },
      ]),
      makeDay('tokyo-5d', 'Day 2', '2026-04-09', 'Ancient Temples & Digital Art', "Step from ancient Asakusa to the futuristic shores of Toyosu — a day that captures Tokyo's range.", [
        {
          title: 'Senso-ji Temple',
          description: 'Wander through the Thunder Gate and up Nakamise-dori, a shop-lined path leading to Tokyo\'s oldest and most visited temple.',
          time: '09:30',
          location: 'Asakusa',
          duration: 120,
          cost: 0,
          currency: 'USD',
          category: 'History' as ActivityCategory,
          aiReason: 'Tokyo\'s oldest temple pairs well with your interest in history and culture.',
        },
        {
          title: 'Tsukiji Outer Market Lunch',
          description: 'Graze the stalls for fresh tamagoyaki, grilled scallops, and premium sushi rolls at this legendary seafood market.',
          time: '12:30',
          location: 'Tsukiji',
          duration: 90,
          cost: 35,
          currency: 'USD',
          category: 'Food' as ActivityCategory,
          aiReason: 'World-class street food scene that fits your food interest and late-start preference.',
        },
        {
          title: 'teamLab Planets',
          description: 'Barefoot immersive digital art installation — wade through a field of flowers, stand inside a crystal universe, and lose yourself in mirror rooms.',
          time: '15:00',
          location: 'Toyosu',
          duration: 120,
          cost: 28,
          currency: 'USD',
          category: 'Culture' as ActivityCategory,
          aiReason: 'An immersive digital art experience that is a hidden gem for most first-timers.',
        },
      ]),
      makeDay('tokyo-5d', 'Day 3', '2026-04-10', 'Harajuku, Shibuya & Nightlife', 'Culture and crowds by day, intimate bar-hopping by night — the full Shibuya-to-Shinjuku sweep.', [
        {
          title: 'Meiji Shrine & Harajuku',
          description: "Start at the serene forest shrine dedicated to Emperor Meiji, then drift into Harajuku's Takeshita-dori for crepes and street fashion.",
          time: '10:00',
          location: 'Shibuya',
          duration: 180,
          cost: 0,
          currency: 'USD',
          category: 'Culture' as ActivityCategory,
          aiReason: 'A peaceful shrine followed by quirky shopping streets covers culture and shopping in one trip.',
        },
        {
          title: 'Shibuya Crossing & Hachiko',
          description: 'Stand at the world\'s busiest pedestrian crossing during rush hour, then find the famous bronze Shiba Inu statue outside Shibuya Station.',
          time: '14:00',
          location: 'Shibuya',
          duration: 60,
          cost: 0,
          currency: 'USD',
          category: 'Culture' as ActivityCategory,
          aiReason: 'Iconic Tokyo landmark — quick and free, fits naturally between Harajuku and dinner.',
        },
        {
          title: 'Golden Gai Bar Hopping',
          description: 'Navigate the six alleys of ramshackle two-story bars, each seating fewer than ten people, and strike up conversation with regulars and owners.',
          time: '20:00',
          location: 'Shinjuku',
          duration: 180,
          cost: 60,
          currency: 'USD',
          category: 'Nightlife' as ActivityCategory,
          aiReason: 'Tiny bars in a historic district — perfect for your nightlife interest.',
        },
      ]),
      makeDay('tokyo-5d', 'Day 4', '2026-04-11', 'Kamakura Day Trip', 'Escape the city for coastal temples, forested hiking trails, and the iconic Great Buddha.', [
        {
          title: 'Day Trip to Kamakura',
          description: 'Take the Yokosuka Line south to this seaside town, visiting the giant bronze Kotoku-in Buddha, Tsurugaoka Hachimangu shrine, and the bamboo grove at Hokoku-ji.',
          time: '08:30',
          location: 'Kamakura',
          duration: 420,
          cost: 50,
          currency: 'USD',
          category: 'Nature' as ActivityCategory,
          aiReason: 'Coastal town with the Great Buddha — history and nature in one balanced day trip.',
        },
        {
          title: 'Ramen Dinner in Shibuya',
          description: 'Recover over a rich tonkotsu bowl at one of Shibuya\'s well-regarded ramen counters — warm, hearty, and easy on the wallet.',
          time: '19:00',
          location: 'Shibuya',
          duration: 90,
          cost: 20,
          currency: 'USD',
          category: 'Food' as ActivityCategory,
          aiReason: 'A casual, budget-friendly dinner after a long day out.',
        },
      ]),
      makeDay('tokyo-5d', 'Day 5', '2026-04-12', 'Farewell & Ginza', 'A memorable final morning of impeccable sushi and upscale souvenir shopping before the airport.', [
        {
          title: 'Tsukiji Sushi Breakfast',
          description: 'Queue up at a renowned standing-sushi bar for nigiri made with the morning\'s freshest catch — a fitting final meal in Japan.',
          time: '08:00',
          location: 'Tsukiji',
          duration: 90,
          cost: 40,
          currency: 'USD',
          category: 'Food' as ActivityCategory,
          aiReason: 'A memorable final meal — sushi at its freshest before your flight.',
        },
        {
          title: 'Souvenir Shopping in Ginza',
          description: 'Browse the flagship stores, department basement food halls, and artisan boutiques of Tokyo\'s most refined shopping district.',
          time: '11:00',
          location: 'Ginza',
          duration: 120,
          cost: 80,
          currency: 'USD',
          category: 'Shopping' as ActivityCategory,
          aiReason: 'Upscale shopping district for last-minute gifts, close to Tokyo Station.',
        },
      ]),
    ],
  },
  {
    id: 'lisbon-4d',
    title: 'Lisbon Long Weekend',
    destination: 'Lisbon, Portugal',
    startDate: '2026-05-22',
    endDate: '2026-05-25',
    budget: 1200,
    currency: 'EUR',
    travelers: 2,
    pace: 'Relaxed',
    interests: ['Food', 'Culture', 'Nature'],
    specialRequests: 'Prefer walkable neighborhoods. Wine tastings welcome.',
    status: 'Confirmed',
    lastUpdated: '2026-04-15T08:00:00Z',
    isDemo: false,
    days: [],
  },
  {
    id: 'bali-7d',
    title: 'Bali Surf & Sun',
    destination: 'Bali, Indonesia',
    startDate: '2026-07-01',
    endDate: '2026-07-07',
    budget: 1800,
    currency: 'USD',
    travelers: 1,
    pace: 'Packed',
    interests: ['Adventure', 'Nature', 'Food', 'Hidden Gems'],
    specialRequests: 'Surfing lessons. Off-the-beaten-path temples.',
    status: 'Planning',
    lastUpdated: '2026-06-28T14:20:00Z',
    isDemo: false,
    days: [],
  },
];
